version: '3.8'
services:
  dockerized_databases:
    container_name: app
    build:
      context: .
      target: base
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/inventory
      - POSTGRES_URL=jdbc:posgresql://postgresserver/user
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver
      - postgresserver

  mysqlserver:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=inventory
      - MYSQL_PASSWORD=inventory
      - MYSQL_DATABASE=inventory
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

  postgresserver:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=user
      - POSTGRES_DB=user
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  mysql_data:
  mysql_config:
  postgres-data:

