database: mysql
spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost/inventory}
    username: ${MYSQL_USER:inventory}
    password: ${MYSQL_PASS:inventory}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true

