spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/basics?allowPublicKeyRetrieval=true
    username: user
    password: pass
    initialization-mode: always
  sql:
    init:
      mode: always

