spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost/inventory}
    username: ${MYSQL_USER:inventory}
    password: ${MYSQL_PASS:inventory}
  sql:
    init:
      mode: always
  jpa:
    database: default
    hibernate:
      ddl-auto: none
    open-in-view: true

postgres:
  datasource:
    url: ${POSTGRES_URL:jdbc:mysql://localhost/user}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASS:user}